### ISSUE TITLE
Getting a JPEG lib mismatch when running pandafium

### ISSUE THREAD

**Issue by abdulg** [gradescope/pdfium#2]
I built `pandafium` on Amazon Linux 2 following the given instructions. The final build step was `ninja -C out/Lambda pandafium` to build just the pandafium binary (building the tests were failing with a `value > MAX_SIZE` error during compile).

When I run the binary to split a PDF I get: `Wrong JPEG library version: library is 62, caller expects 80` on the command line. I am using the libjpeg-turbo package as instructed (although I had to also install the static library) and that is version 6:
```
[ec2-user@ip-10-0-254-136 tests]$ ll /usr/lib64//libjpeg.*
-rw-r--r-- 1 root root 446568 Apr 22 16:58 /usr/lib64//libjpeg.a
lrwxrwxrwx 1 root root     17 Jun  3 19:10 /usr/lib64//libjpeg.so -> libjpeg.so.62.1.0
lrwxrwxrwx 1 root root     17 Jun  3 19:10 /usr/lib64//libjpeg.so.62 -> libjpeg.so.62.1.0
-rwxr-xr-x 1 root root 281096 Apr 22 16:58 /usr/lib64//libjpeg.so.62.1.0
```

Any pointers on how to proceed to fix this?

**Comment by ibrahima** [comment]
Hi! Sorry for the late response, but I believe this has been resolved in https://github.com/gradescope/pdfium/pull/3/files#diff-ceb079f66233f921b5de6e901dcc7a72L5

If you still need this, please let us know if that works for you!

Note that there's now a Dockerfile to build the binary for Amazon Lambda/Amazon Linux as well.
